interface Env { DB: D1Database }
const ORIGIN = 'https://turbodiazzz-star.github.io';
const empty: any = { version: 4, updatedAt: new Date(0).toISOString(), gyms: [], machines: [], sessions: [], inbody: [], photos: [], aiReports: [], deletedInbodyIds: [], deletedPhotoIds: [], deletedSessionIds: [], deletedGymIds: [], deletedMachineIds: [] };
const keys = ['gyms','machines','sessions','inbody','photos','aiReports'];
function hs(){ return new Headers({'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET, PUT, OPTIONS','Cache-Control':'no-store','Vary':'Origin'}); }
function out(r:Request,b:any,s=200){const h=hs();h.set('Content-Type','application/json; charset=utf-8');return new Response(JSON.stringify(b),{status:s,headers:h});}
function merge(a:any[] = [], b:any[] = [], d:string[] = []){const m=new Map();[...a,...b].forEach(x=>x?.id&&m.set(x.id,x));return [...m.values()].filter(x=>!d.includes(x.id));}
function combine(old:any, inc:any){const o={...empty,...old,...inc,updatedAt:new Date().toISOString()};for(const k of keys){const dk='deleted'+k[0].toUpperCase()+k.slice(1)+'Ids';o[k]=merge(old?.[k],inc?.[k],o[dk]||[]);}for(const k of ['deletedInbodyIds','deletedPhotoIds','deletedSessionIds','deletedGymIds','deletedMachineIds'])o[k]=[...new Set([...(old?.[k]||[]),...(inc?.[k]||[])])];for(const k of keys){const dk='deleted'+k[0].toUpperCase()+k.slice(1)+'Ids';o[k]=merge(old?.[k],inc?.[k],o[dk]||[]);}return o;}
export default {async fetch(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:hs()});const u=new URL(request.url);if(u.pathname!=='/state'||!['GET','PUT'].includes(request.method))return out(request,{error:'Not found'},404);if(request.method==='PUT'&&request.headers.get('Origin')!==ORIGIN)return out(request,{error:'origin denied'},403);try{const row=await env.DB.prepare('SELECT payload FROM app_state WHERE id=1').first<any>();const cur=row?JSON.parse(row.payload):empty;if(request.method==='GET')return out(request,cur);const snap=combine(cur,await request.json());await env.DB.prepare('INSERT INTO app_state (id,payload,updated_at) VALUES (1,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload, updated_at=excluded.updated_at').bind(JSON.stringify(snap),snap.updatedAt).run();return out(request,{ok:true,snapshot:snap});}catch(e){return out(request,{error:e instanceof Error?e.message:'server error'},500);}}};
